[package]
name = "channelz"
version = "0.0.1"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "Generate static Brotli and Gzip encodings of a file or directory."

[dependencies]
brotli = "3.3.0"
rayon = "1.3.*"
walkdir = "2.2.*"

[dependencies.flate2]
version = "1.0"
default-features = false
features = ["cloudflare_zlib"]

[dependencies.clap]
version = "2.33.*"
default-features = false
features = [ "color", "suggestions", "vec_map", "wrap_help" ]
