[package]
name = "channelz"
version = "0.0.5"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "ChannelZ is a simple, fast, multi-threaded static Gzip/Brotli encoding tool for the CLI."
build = "build.rs"

[build-dependencies]
clap = "2.33.*"

[dependencies]
fyi_core = { git = "https://github.com/Blobfolio/fyi.git", features=[ "progress", "witcher" ] }
regex = "1.3.6"
rayon = "1.3.*"

[dependencies.compu]
version = "0.5.1"
default-features = false
features = ["brotli-c", "zlib-opt"]

[dependencies.clap]
version = "2.33.*"
default-features = false
features = [ "color", "vec_map" ]
