[package]
name = "channelz"
version = "1.0.0"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "ChannelZ is a simple, fast, multi-threaded static Gzip/Brotli encoding tool for the CLI."
build = "build.rs"
publish = false

[build-dependencies]
clap = "2.33.*"

[dependencies]
regex = "1.3.6"
rayon = "1.3.*"

[dependencies.compu]
version = "0.5.1"
default-features = false
features = ["brotli-c", "zlib-opt"]

[dependencies.clap]
version = "2.33.*"
default-features = false
features = [ "color", "suggestions", "vec_map", "wrap_help" ]

[dependencies.fyi_core]
git = "https://github.com/Blobfolio/fyi.git"
branch = "master"
default-features = false
features = [ "progress", "witcher" ]
