[package]
name = "channelz"
version = "0.1.2"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "ChannelZ is a simple, fast, multi-threaded static Gzip/Brotli encoding tool for the CLI."
build = "build.rs"
publish = false

[package.metadata.deb]
maintainer = "Josh Stoik <hello@blobfolio.com>"
copyright = "2020, Blobfolio, LLC <hello@blobfolio.com>"
license-file = ["../LICENSE", "0"]
revision = "1"
depends = "$auto"
section = "utility"
extended-description = """\
ChannelZ is a simple, fast, multi-threaded static Gzip/Brotli \
encoding tool for the CLI. \
. \
Point it toward a single file to generate maximally-compressed Brotli- and \
Gzip-encoded copies, or point it toward a directory to recursively handle many \
files en masse. \
. \
In directory mode, only files with the following extensions will be looked at: \
css; htm(l); ico; js; json; mjs; svg; txt; xhtm(l); xml; xsl"""
assets = [
    ["target/release/channelz", "usr/bin/", "755"],
    ["../release/completions/channelz.bash", "etc/bash_completion.d/", "644"],
    ["../release/man/channelz.1.gz", "usr/share/man/man1/", "644"],
]

[build-dependencies]
clap = { version = "2.33.*", default-features = false }

[dependencies]
rayon = "1.3.*"

[dependencies.compu]
version = "0.5.1"
default-features = false
features = ["brotli-c", "zlib-opt"]

[dependencies.clap]
version = "2.33.*"
default-features = false
features = [ "color", "suggestions", "vec_map", "wrap_help" ]

[dependencies.fyi_core]
git = "https://github.com/Blobfolio/fyi.git"
branch = "master"
default-features = false
features = [ "progress", "witcher" ]
