[package]
name = "channelz"
version = "0.0.1"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "Generate maximally-compressed Gzip- and Brotli-encoded copies of a file or recurse a directory to do it for many files at once."

[dependencies]
brotli = "3.3.*"
rayon = "1.3.*"
regex = "1.3.*"
walkdir = "2.3.1"

[dependencies.flate2]
version = "1.0"
default-features = false
features = ["cloudflare_zlib"]

[dependencies.clap]
version = "2.33.*"
default-features = false
features = [ "color" ]
