[package]
name = "channelz_core"
version = "0.3.5"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "ChannelZ is a simple, fast, multi-threaded static Gzip/Brotli encoding tool for the CLI."
publish = false

[dependencies]
libdeflater = "0.5.*"

[dependencies.compu]
version = "0.5.*"
default-features = false
features = [ "brotli-c" ]

[dev-dependencies]
criterion = "*"

[[bench]]
name = "encode"
harness = false
