.TH "CHANNELZ" "1" "November 2020" "ChannelZ v0.4.1" "User Commands"
.SH NAME
ChannelZ \- Manual page for channelz v0.4.1.
.SH DESCRIPTION
ChannelZ is a simple, fast, multi\-threaded static Gzip/Brotli encoding tool for the CLI.
.SS USAGE:
.TP
channelz [FLAGS] [OPTIONS] <PATH(s)…>
.SS FLAGS:
.TP
\fB\-\-clean\fR
Remove all existing *.gz *.br files before starting.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-p\fR, \fB\-\-progress\fR
Show progress bar while working.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version.
.SS OPTIONS:
.TP
\fB\-l\fR, \fB\-\-list\fR <FILE>
Read file paths from this text file.
.SS <PATH(S)…>:
.TP
Any number of files and directories to crawl and crunch.
.SH FILE TYPES
Static copies will only be generated for files with these extensions:
.RE
css; eot; htm(l); ico; js; json; mjs; otf; rss; svg; ttf; txt; xhtm(l); xml; xsl
