.TH "CHANNELZ" "1" "April 2022" "ChannelZ v0.5.12" "User Commands"
.SH NAME
ChannelZ \- Manual page for channelz v0.5.12.
.SH DESCRIPTION
Fast, multi\-threaded static Gzip/Brotli encoding tool for the CLI.
.SS USAGE:
.TP
channelz [FLAGS] [OPTIONS] <PATH(s)…>
.SS FLAGS:
.TP
\fB\-\-clean\fR
Remove all existing *.gz *.br files (of types ChannelZ would encode) before starting.
.TP
\fB\-\-clean\-only\fR
Same as \-\-clean, but exit immediately afterward.
.TP
\fB\-\-force\fR
Try to encode ALL files passed to ChannelZ, regardless of file extension (except those already ending in .br/.gz). Be careful with this!
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information and exit.
.TP
\fB\-p\fR, \fB\-\-progress\fR
Show progress bar while minifying.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information and exit.
.SS OPTIONS:
.TP
\fB\-l\fR, \fB\-\-list\fR <FILE>
Read (absolute) file and/or directory paths from this text file, one entry per line.
.SS <PATH(S)…>:
.TP
One or more file and/or directory paths to compress and/or (recursively) crawl.
.SH FILE TYPES
Static copies will only be generated for files with these extensions:
.RE
appcache; atom; bmp; css; eot; geojson; htc; htm(l); ico; ics; js; json;
.RE
jsonld; manifest; md; mjs; otf; rdf; rss; svg; ttf; txt; vcard; vcs; vtt;
.RE
wasm; webmanifest; xhtm(l); xml; xsl
