/*!
# ChannelZ
*/

#![forbid(unsafe_code)]

#![deny(
	clippy::allow_attributes_without_reason,
	clippy::correctness,
	unreachable_pub,
)]

#![warn(
	clippy::complexity,
	clippy::nursery,
	clippy::pedantic,
	clippy::perf,
	clippy::style,

	clippy::allow_attributes,
	clippy::clone_on_ref_ptr,
	clippy::create_dir,
	clippy::filetype_is_file,
	clippy::format_push_string,
	clippy::get_unwrap,
	clippy::impl_trait_in_params,
	clippy::lossy_float_literal,
	clippy::missing_assert_message,
	clippy::missing_docs_in_private_items,
	clippy::needless_raw_strings,
	clippy::panic_in_result_fn,
	clippy::pub_without_shorthand,
	clippy::rest_pat_in_fully_bound_structs,
	clippy::semicolon_inside_block,
	clippy::str_to_string,
	clippy::string_to_string,
	clippy::todo,
	clippy::undocumented_unsafe_blocks,
	clippy::unneeded_field_pattern,
	clippy::unseparated_literal_suffix,
	clippy::unwrap_in_result,

	macro_use_extern_crate,
	missing_copy_implementations,
	missing_docs,
	non_ascii_idents,
	trivial_casts,
	trivial_numeric_casts,
	unused_crate_dependencies,
	unused_extern_crates,
	unused_import_braces,
)]

#![expect(clippy::doc_markdown, reason = "`ChannelZ` makes this annoying.")]
#![expect(clippy::redundant_pub_crate, reason = "Unresolvable.")]



mod abacus;
mod enc;
mod err;
mod ext;



use abacus::{
	EncoderTotals,
	ThreadTotals,
};
use argyle::Argument;
use crossbeam_channel::Receiver;
use dactyl::NiceU64;
use dowser::Dowser;
use err::ChannelZError;
use fyi_ansi::dim;
use fyi_msg::{
	Msg,
	MsgKind,
	Progless,
};
use std::{
	num::NonZeroUsize,
	os::unix::ffi::OsStrExt,
	path::{
		Path,
		PathBuf,
	},
	process::ExitCode,
	sync::atomic::Ordering::SeqCst,
	thread,
};



// Flags generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/flags.rs"));

/// # Extension: Brotli.
const EXT_BR: u16 = u16::from_le_bytes([b'b', b'r']);

/// # Extension: Gzip.
const EXT_GZ: u16 = u16::from_le_bytes([b'g', b'z']);



/// # Main.
fn main() -> ExitCode {
	match main__() {
		Ok(()) => ExitCode::SUCCESS,
		Err(e @ (ChannelZError::PrintHelp | ChannelZError::PrintVersion)) => {
			println!("{e}");
			ExitCode::SUCCESS
		},
		Err(e) => {
			Msg::error(e.to_string()).eprint();
			ExitCode::FAILURE
		},
	}
}

#[inline]
/// # Actual Main.
fn main__() -> Result<(), ChannelZError> {
	let args = argyle::args()
		.with_keywords(include!(concat!(env!("OUT_DIR"), "/argyle.rs")));

	let mut kinds = Flags::All;
	let mut paths = Dowser::default();
	let mut progress = false;
	for arg in args {
		match arg {
			Argument::Key("--clean") => { kinds.set(Flags::Clean); },
			Argument::Key("--clean-only") => { kinds.set(Flags::CleanOnly); },
			Argument::Key("--force") => { kinds.set(Flags::Force); },
			Argument::Key("--no-br") => { kinds.unset(Flags::Brotli); },
			Argument::Key("--no-gz") => { kinds.unset(Flags::Gzip); },
			Argument::Key("-p" | "--progress") => { progress = true; },

			Argument::Key("-h" | "--help") => return Err(ChannelZError::PrintHelp),
			Argument::Key("-V" | "--version") => return Err(ChannelZError::PrintVersion),

			Argument::KeyWithValue("-l" | "--list", s) => {
				paths.read_paths_from_file(s).map_err(|_| ChannelZError::ListFile)?;
			},

			// Assume paths.
			Argument::Path(s) => { paths = paths.with_path(s); },

			// Mistakes?
			Argument::Other(s) => return Err(ChannelZError::InvalidCli(s)),
			Argument::InvalidUtf8(s) => return Err(ChannelZError::InvalidCli(s.to_string_lossy().into_owned())),

			// Nothing else is expected.
			_ => {},
		}
	}

	// Nothing?
	kinds.contains_any(Flags::All).ok_or(ChannelZError::NoEncoders)?;

	// Clean first?
	if kinds.contains(Flags::Clean) {
		clean(paths.clone(), progress, kinds);
		if kinds.contains(Flags::CleanOnly) { return Ok(()); }
	}

	// Put it all together!
	let mut paths: Vec<PathBuf> =
		if kinds.contains(Flags::Force) { paths.filter(find_all).collect() }
		else { paths.filter(find_default).collect() };
	let total = NonZeroUsize::new(paths.len()).ok_or(ChannelZError::NoFiles)?;
	paths.sort();

	// How many threads?
	let threads = thread::available_parallelism().map_or(
		NonZeroUsize::MIN,
		|t| NonZeroUsize::min(t, total),
	);

	// Set up the killswitch.
	let killed = Progless::sigint_two_strike();

	// Boot up a progress bar, if desired.
	let progress =
		if progress {
			Progless::try_from(total)
				.ok()
				.map(|p| p.with_reticulating_splines("ChannelZ"))
		}
		else { None };

	// Thread business!
	let (tx, rx) = crossbeam_channel::bounded::<&Path>(threads.get());
	let len = thread::scope(#[inline(always)] |s| {
		// Set up the worker threads.
		let mut workers = Vec::with_capacity(threads.get());
		for _ in 0..threads.get() {
			workers.push(s.spawn(#[inline(always)] || crunch(&rx, kinds, progress.as_ref())));
		}

		// Push all the files to it, then drop the sender to disconnect.
		for path in &paths {
			if killed.load(SeqCst) || tx.send(path).is_err() { break; }
		}
		drop(tx);

		// Sum the totals as each thread finishes.
		// TODO: prefer try_reduce() when stable.
		workers.into_iter()
			.try_fold(ThreadTotals::new(), |acc, worker|
				worker.join().map(|len2| acc + len2)
			)
			.map_err(|_| ChannelZError::Jobserver)
	})?;
	drop(rx);

	// Summarize?
	if let Some(progress) = progress {
		progress.finish();
		progress.summary(MsgKind::Crunched, "file", "files").print();
		len.summarize(kinds);
	}

	// Early abort?
	if killed.load(SeqCst) { Err(ChannelZError::Killed) }
	else { Ok(()) }
}

/// # Clean.
///
/// This will run a separate search over the specified paths with the sole
/// purpose of removing `*.gz` and/or `*.br` files.
fn clean(paths: Dowser, summary: bool, kinds: Flags) {
	let has_br = kinds.contains(Flags::Brotli);
	let has_gz = kinds.contains(Flags::Gzip);

	let mut cleaned = 0_u64;
	for p in paths {
		let [rest @ .., b'.', y, z] = p.as_os_str().as_bytes() else { continue; };
		let ext = u16::from_le_bytes([y.to_ascii_lowercase(), z.to_ascii_lowercase()]);
		if
			((has_br && ext == EXT_BR) || (has_gz && ext == EXT_GZ)) &&
			ext::match_extension(rest)
		{
			if std::fs::remove_file(&p).is_ok() { cleaned += 1; }
			else {
				Msg::warning(format!(
					concat!("Unable to delete ", dim!("{p}")),
					p=p.display(),
				)).eprint();
			}
		}
	}

	if summary {
		if cleaned == 0 { Msg::info("There was nothing to clean.") }
		else {
			Msg::success(format!(
				"Removed {} old {}-encoded {}.",
				NiceU64::from(cleaned),
				if has_br && has_gz { "br/gz" }
				else if has_br { "br" }
				else { "gz" },
				if cleaned == 1 { "copy" } else { "copies" },
			))
		}
		.print();
	}
}

#[inline(never)]
/// # Worker Callback.
///
/// This is the worker callback for crunching. It listens for "new" file paths
/// and crunches them — and maybe updates the progress bar, etc. — then quits
/// as soon as the work has dried up.
fn crunch(rx: &Receiver::<&Path>, kinds: Flags, progress: Option<&Progless>) -> ThreadTotals {
	let mut enc = enc::Encoder::new(kinds);
	let mut len = ThreadTotals::new();

	let Some(progress) = progress else {
		while let Ok(p) = rx.recv() { let _res = enc.encode(p); }
		return len;
	};

	while let Ok(p) = rx.recv() {
		let name = p.to_string_lossy();
		progress.add(&name);

		if let Some(len2) = enc.encode(p) { len += len2; }

		progress.remove(&name);
	}

	len
}

#[cold]
#[expect(clippy::ptr_arg, reason = "Needs to match filter() signature.")]
/// # Find Non-GZ/BR.
///
/// This is a callback for `Dowser`. That library ensures the paths passed will
/// be valid, canonical _files_; all we need to do is check the extensions.
///
/// For this variation, everything is fair game so long as it isn't already
/// `gz`/`br`-encoded.
fn find_all(p: &PathBuf) -> bool { ! ext::match_encoded(p.as_os_str().as_bytes()) }

#[expect(clippy::ptr_arg, reason = "Needs to match filter() signature.")]
/// # Find Default.
///
/// This is a callback for `Dowser`. That library ensures the paths passed will
/// be valid, canonical _files_; all we need to do is check the extensions.
///
/// For this variation, we're looking for all the hard-coded "default" types.
/// Refer to the main documentation or help screen for that list.
fn find_default(p: &PathBuf) -> bool { ext::match_extension(p.as_os_str().as_bytes()) }
